/** Wonderplugin Tabs Plugin Pro Version
 * Copyright 2019 Magic Hills Pty Ltd All Rights Reserved
 * Website: http://www.wonderplugin.compmr  ptmr
 * Version 7.2 
 */
if(typeof wonderpluginTabsObjects==="undefined")var wonderpluginTabsObjects=new function(){this.objects=[];this.addObject=function(obj){this.objects.push(obj)}};
(function($){$.fn.wonderplugintabs=function(options){var WonderPluginTabs=function(container,options,id){this.container=container;this.options=options;this.id=id;this.isOpera=navigator.userAgent.match(/Opera/i)!=null||navigator.userAgent.match(/OPR\//i)!=null;this.isIE11=navigator.userAgent.match(/Trident\/7/)!=null&&navigator.userAgent.match(/rv:11/)!=null;this.isIE=navigator.userAgent.match(/MSIE/i)!=null&&!this.isOpera||this.isIE11;this.isAndroid=navigator.userAgent.match(/Android/i)!=null;this.isIPad=
navigator.userAgent.match(/iPad/i)!=null;this.isIPhone=navigator.userAgent.match(/iPod/i)!=null||navigator.userAgent.match(/iPhone/i)!=null;this.isIOS=this.isIPad||this.isIPhone;this.isMobile=this.isAndroid||this.isIPad||this.isIPhone;this.options.skinsfolder=this.options.skinsfoldername;if(this.options.skinsfolder.length>0&&this.options.skinsfolder[this.options.skinsfolder.length-1]!="/")this.options.skinsfolder+="/";if(this.options.skinsfolder.charAt(0)!="/"&&this.options.skinsfolder.substring(0,
5)!="http:"&&this.options.skinsfolder.substring(0,6)!="https:")this.options.skinsfolder=this.options.jsfolder+this.options.skinsfolder;this.container.css({"display":"block"});this.accordionmode=this.options.accordion;if(this.options.accordiononsmallscreen)this.options.fullwidthtabsonsmallscreen=true;if(!this.accordionmode&&this.options.accordiononsmallscreen){var screenWidth=$(window).width();if(screenWidth<this.options.fullwidthtabsonsmallscreenwidth)this.accordionmode=true}if(this.options.enablega&&
this.options.gatrackingid&&!window.ga){(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date;a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create",this.options.gatrackingid,"auto")}this.init()};WonderPluginTabs.prototype={createNavs:function(){if(this.options.navstyle=="none")return;
var panels=this.getTabElem(".wonderplugintabs-panel-wrap",this.container);var navContainer=this.options.navinsidepanels?panels:this.container;this.nav=$('<div class="wonderplugintabs-nav" style="'+this.options.navcss+'"></div>');this.nav.appendTo(navContainer);if(!this.options.navinsidepanels&&this.options.navinpanelscenter){var offset=panels.position().left;this.nav.css({"padding-left":offset+"px"})}this.bulletList=$('<div class="wonderplugintabs-bullet-list"></div>');this.bulletList.css({display:"inline-block",
margin:"0 auto"});this.bulletList.appendTo(this.nav);this.bullets=[];var totalTabs=this.getTotalTabs();for(var i=0;i<totalTabs;i++){var bullet=this.createNavBullet(i);bullet.appendTo(this.bulletList);this.bullets.push(bullet)}this.updateNavs()},createNavBullet:function(index){var instance=this;var bullet=$('<div class="wonderplugintabs-bullet wonderplugintabs-bullet-'+index+'" data-bulletindex="'+index+'"></div>');bullet.css({overflow:"hidden",cursor:"pointer",display:"inline-block","margin-left":this.options.navspacing+
"px",width:this.options.navwidth+"px",height:this.options.navheight+"px",background:"url('"+this.options.navimage+"') no-repeat left top"});bullet.hover(function(){$(this).css({"background-position":"left bottom"})},function(){if(instance.getActiveId()!=$(this).data("bulletindex"))$(this).css({"background-position":"left top"})});bullet.on("click",function(){var tabId=$(this).data("bulletindex");instance.switchToId(tabId)});return bullet},updateNavs:function(){if(this.options.navstyle=="none")return;
this.updateNavsOnResponsive();var tabId=this.getActiveId();for(var i=0;i<this.bullets.length;i++)if(i==tabId)this.bullets[i].css({"background-position":"left bottom"});else this.bullets[i].css({"background-position":"left top"})},updateNavsOnResponsive:function(){if(this.options.navstyle=="none")return;this.nav.css({display:this.options.hidenavinaccordionmode&&this.accordionmode?"none":"block"})},createArrows:function(){if(this.options.arrowstyle=="none")return;var instance=this;var arrowsContainer=
this.options.arrowinsidepanel?this.getTabElem(".wonderplugintabs-panel-wrap",this.container):this.container;this.prevArrow=$('<div class="wonderplugintabs-prev" style="'+this.options.prevarrowcss+'"></div>');this.prevArrow.appendTo(arrowsContainer);this.nextArrow=$('<div class="wonderplugintabs-next" style="'+this.options.nextarrowcss+'"></div>');this.nextArrow.appendTo(arrowsContainer);this.prevArrow.css({overflow:"hidden",cursor:"pointer",width:this.options.arrowwidth+"px",height:this.options.arrowheight+
"px",background:"url('"+this.options.arrowimage+"') no-repeat left top"});this.nextArrow.css({overflow:"hidden",cursor:"pointer",width:this.options.arrowwidth+"px",height:this.options.arrowheight+"px",background:"url('"+this.options.arrowimage+"') no-repeat right top"});this.prevArrow.hover(function(){$(this).css({"background-position":"left bottom"})},function(){$(this).css({"background-position":"left top"})});this.nextArrow.hover(function(){$(this).css({"background-position":"right bottom"})},
function(){$(this).css({"background-position":"right top"})});if(this.options.arrowstyle=="always"){this.prevArrow.css({display:"block"});this.nextArrow.css({display:"block"})}else{this.prevArrow.css({display:"none"});this.nextArrow.css({display:"none"});arrowsContainer.hover(function(){if(!instance.prevArrow.data("ishidden"))instance.prevArrow.fadeIn();if(!instance.nextArrow.data("ishidden"))instance.nextArrow.fadeIn()},function(){instance.prevArrow.fadeOut();instance.nextArrow.fadeOut()})}this.prevArrow.click(function(){var tabId=
instance.getActiveId()-1;if(tabId<0)if(!instance.options.arrowloop)return;else tabId=instance.getTotalTabs()-1;instance.switchToId(tabId)});this.nextArrow.click(function(){var tabId=instance.getActiveId()+1;if(tabId>=instance.getTotalTabs())if(!instance.options.arrowloop)return;else tabId=0;instance.switchToId(tabId)});this.updateArrows()},updateArrows:function(){if(this.options.arrowstyle=="none")return;var tabId=this.getActiveId();var totalTabs=this.getTotalTabs();if(tabId==totalTabs-1&&!this.options.arrowloop){this.nextArrow.css({display:"none"});
this.nextArrow.data("ishidden",1)}else{this.nextArrow.css({display:"block"});this.nextArrow.data("ishidden",0)}if(tabId==0&&!this.options.arrowloop){this.prevArrow.css({display:"none"});this.prevArrow.data("ishidden",1)}else{this.prevArrow.css({display:"block"});this.prevArrow.data("ishidden",0)}},getParams:function(){var result={};var params=window.location.search.substring(1).split("&");for(var i=0;i<params.length;i++){var value=params[i].split("=");if(value&&value.length==2)result[value[0].toLowerCase()]=
unescape(value[1])}return result},getTabElem:function(classname,container){switch(classname){case ".wonderplugintabs-header-wrap":classname="> .wonderplugintabs-header-wrap";break;case ".wonderplugintabs-header-inner-wrap":case ".wonderplugintabs-header-ul":case ".wonderplugintabs-header-li":case ".wonderplugintabs-header-caption":case ".wonderplugintabs-header-title":case ".wonderplugintabs-header-menu":case ".wonderplugintabs-header-prev":case ".wonderplugintabs-header-next":case ".wonderplugintabs-header-li-first":case ".wonderplugintabs-header-li-last":case ".wonderplugintabs-header-menu-dropdown":case ".wonderplugintabs-header-menu-dropdown-item":classname=
"> .wonderplugintabs-header-wrap "+classname;break;case ".wonderplugintabs-panel-wrap":classname="> .wonderplugintabs-panel-wrap";break;case ".wonderplugintabs-panel":classname=this.accordionmode?"> .wonderplugintabs-header-wrap .wonderplugintabs-panel":"> .wonderplugintabs-panel-wrap > .wonderplugintabs-panel";break;case ".wonderplugintabs-panel-active":classname=this.accordionmode?"> .wonderplugintabs-header-wrap .wonderplugintabs-panel-active":"> .wonderplugintabs-panel-wrap > .wonderplugintabs-panel-active";
break}var items=$(classname,container);for(var i=items.length-1;i>=0;i--){var parent=$(items[i]).closest(".wonderplugintabs");if(parent&&$(parent).length>0&&$(parent).attr("id")!="wonderplugin-tabs-preview"&&$(parent).data("tabsid")!=this.id)items.splice(i,1)}return items},init:function(){var inst=this;if(this.accordionmode)this.applyAccordion();this.container.css({position:"relative"});if(this.options.fullwidth)this.container.css({"max-width":"100%"});else if(this.options.responsive)this.container.css({"max-width":this.options.width+
"px"});else this.container.css({width:this.options.width+"px"});var $header_li=this.getTabElem(".wonderplugintabs-header-li",this.container);if(this.options.fixedheaderwidth)$header_li.css({width:this.accordionmode?"auto":this.options.headerwidth});if(this.options.fixedheaderheight)$header_li.css({height:this.accordionmode?"auto":this.options.headerheight});var firstid=this.options.firstid;if(this.options.closeall)firstid=-1;if(this.accordionmode&&this.options.accordioncloseall)firstid=-1;if(this.options.savestatusincookie&&
$.wptCookie("wonderplugin_tabs_"+this.id+"_id"))firstid=$.wptCookie("wonderplugin_tabs_"+this.id+"_id");var params=this.getParams();var tabIdParam=parseInt(params["tabid"+this.id]);var paramValue=parseInt(params["tabid"]);var groupId=parseInt(params["tabgroupid"]);if(!isNaN(tabIdParam)&&tabIdParam>=0&&tabIdParam<$header_li.length)firstid=tabIdParam;else if(!isNaN(paramValue)&&paramValue>=0&&paramValue<$header_li.length)if(isNaN(groupId)||groupId==this.id)firstid=paramValue;var tabSlugParam=params["tab"+
this.id]?params["tab"+this.id]:params["tab"]?params["tab"]:"";if(tabSlugParam)this.getTabElem(".wonderplugintabs-header-li",this.container).each(function(index){if($(this).data("slug")==tabSlugParam){firstid=index;return false}});if(isNaN(firstid))firstid=0;if(firstid>=$header_li.length)firstid=$header_li.length-1;if(this.options.oninit&&window[this.options.oninit]&&typeof window[this.options.oninit]=="function")window[this.options.oninit](firstid);this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid",
firstid);if(firstid>=0)$header_li.eq(firstid).addClass("wonderplugintabs-header-li-active");this.getTabElem(".wonderplugintabs-panel",this.container).each(function(index){if(index==firstid)$(this).addClass("wonderplugintabs-panel-active").css({display:"block",visibility:"visible",opacity:1});else{if(inst.options.applydisplaynonetohiddenpanel)$(this).css({display:"none"});$(this).css({visibility:"hidden",opacity:0})}});if(firstid>=0){if(firstid==0)$header_li.eq(firstid).addClass("wonderplugintabs-header-li-active-first");
if(firstid==$header_li.length-1)$header_li.eq(firstid).addClass("wonderplugintabs-header-li-active-last");var prev_tab=firstid-1;if(prev_tab>=0)$header_li.eq(prev_tab).addClass("wonderplugintabs-header-li-prev");var next_tab=firstid+1;if(next_tab<$header_li.length)$header_li.eq(next_tab).addClass("wonderplugintabs-header-li-next")}this.switchTabs();var i;var l;var d0="wmoangdiecrpluginh.iclolms";for(i=1;i<=5;i++)d0=d0.slice(0,i)+d0.slice(i+1);l=d0.length;for(var i=0;i<5;i++)d0=d0.slice(0,l-9+i)+d0.slice(l-
8+i);if(this.options.stamp!="AM"+"Com"&&window.location.href.indexOf(d0)<0){var mk='<a href="'+inst.options.marklink+'" target="_blank"><div style="display:block;visibility:visible;z-index:999;position:absolute;bottom:4px;right:4px;padding:3px;border-radius:3px;-moz-border-radius:3px;-webkit-border-radius:3px;background-color:#777;color:#fff;font:12px Arial,sans-serif;">'+inst.options.mark+"</div></a>";this.getTabElem(".wonderplugintabs-panel",this.container).append(mk)}this.createArrows();this.createNavs();
this.addNav();this.applyResponsive();this.adjustPanelHeight();$(window).resize(function(){setTimeout(function(){inst.applyResponsive()},inst.options.resizedelay)});$(window).trigger("inited.wonderplugintabs",[this.id,firstid]);if(this.options.triggerresizeonload)setTimeout(function(){$(window).trigger("resize")},this.options.triggerresizeonloadtimeout);if(this.options.ajaxloading)this.ajaxLoadingTab(firstid);if(this.options.keyaccess)$(document).keyup(function(e){if(e.keyCode==37)inst.switchPrev();
else if(e.keyCode==39)inst.switchNext()});if(this.options.enabletabindex)$(".wonderplugintabs-header-caption, .wonderplugintabs-header-menu",this.container).attr("tabindex","0").keyup(function(e){if(e.keyCode==13)$(this).trigger("click")})},applyAccordion:function(){this.container.addClass("wonderplugintabs-accordionmode");var $panels=this.getTabElem(".wonderplugintabs-panel-wrap",this.container);$panels.css({display:"none"});var instance=this;var items=$(".wonderplugintabs-panel",$panels);for(var i=
items.length-1;i>=0;i--){var parent=$(items[i]).closest(".wonderplugintabs");if(parent&&$(parent).length>0&&$(parent).attr("id")!="wonderplugin-tabs-preview"&&$(parent).data("tabsid")!=this.id)items.splice(i,1)}if(instance.options.direction=="horizontal")instance.getTabElem(".wonderplugintabs-header-ul",instance.container).css({"margin-left":0});else instance.getTabElem(".wonderplugintabs-header-ul",instance.container).css({"margin-top":0});items.each(function(index){instance.getTabElem(".wonderplugintabs-header-li",
instance.container).eq(index).append($(this))})},reverseAccordion:function(){this.container.removeClass("wonderplugintabs-accordionmode");var instance=this;instance.getTabElem(".wonderplugintabs-header-li",instance.container).each(function(index){instance.getTabElem(".wonderplugintabs-panel-wrap",instance.container).append($(".wonderplugintabs-panel",this))});var tabid=instance.getTabElem(".wonderplugintabs-header-ul",instance.container).data("activeid");if(tabid<0&&instance.options.closeall)instance.getTabElem(".wonderplugintabs-panel-wrap",
instance.container).css({display:"none"});else{instance.getTabElem(".wonderplugintabs-panel-wrap",instance.container).css({display:"block"});if(tabid<0)instance.switchToId(0)}},addHorFloat:function(){var $header_ul=this.getTabElem(".wonderplugintabs-header-ul",this.container);if(this.options.horizontaltabalign=="left")$header_ul.css({"float":"left"});else if(this.options.horizontaltabalign=="right")$header_ul.css({"float":"right"});else if(this.options.horizontaltabalign=="center"){$header_ul.css({"text-align":"center"});
$header_ul.css({"float":"none"})}},addNav:function(){var inst=this;var $header_wrap=this.getTabElem(".wonderplugintabs-header-wrap",this.container);if(this.options.addpanelarrow){this.getTabElem(".wonderplugintabs-panel-wrap",this.container).append('<div class="wonderplugintabs-panel-wrap-arrow"></div>');$(window).on("inited.wonderplugintabs afterswitch.wonderplugintabs carouselanimationfinished.wonderplugintabs.wonderplugintabs",function(event,id){if(id!=inst.id)return;var pos=inst.getActiveTabCenterPos();
inst.getTabElem(".wonderplugintabs-panel-wrap-arrow",inst.container).css({display:pos<=0||pos>=inst.getTotalHeaderWidth()?"none":"block",left:pos+"px"})})}if(this.options.responsivemode=="arrow"){var $header_prev=$('<div class="wonderplugintabs-header-prev '+this.options.arrowprevicon+'"></div>');var $header_next=$('<div class="wonderplugintabs-header-next '+this.options.arrownexticon+'"></div>');$header_wrap.prepend($header_prev).append($header_next);$(".wonderplugintabs-header-prev, .wonderplugintabs-header-next",
this.container).css({"font-size":this.options.arrowfontsize+"px","color":this.options.arrowfontcolor});$header_prev.click(function(){if(inst.options.tabarrowmode=="switch")inst.switchPrev();else if(inst.options.direction=="horizontal"){var w0=inst.getTabElem(".wonderplugintabs-header-inner-wrap",inst.container).width();var ml=Math.abs(parseFloat(inst.getTabElem(".wonderplugintabs-header-ul",inst.container).css("margin-left")));var m0=ml-w0;var w1=inst.calcHeaderUlWidth();if(Math.floor(ml)<=0&&inst.options.carouselloop)inst.getTabElem(".wonderplugintabs-header-ul",
inst.container).animate({"margin-left":String(w0-w1)+"px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])});else{if(m0<0){m0=0;if(!inst.options.carouselloop)$header_prev.css({display:"none"})}inst.getTabElem(".wonderplugintabs-header-ul",inst.container).animate({"margin-left":"-"+m0+"px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])})}if(!inst.options.carouselloop)$header_next.css({display:"block"})}else{var h0=
inst.getTabElem(".wonderplugintabs-header-inner-wrap",inst.container).height();var m0=Math.abs(parseFloat(inst.getTabElem(".wonderplugintabs-header-ul",inst.container).css("margin-top")))-h0;if(m0<0)m0=0;inst.getTabElem(".wonderplugintabs-header-ul",inst.container).animate({"margin-top":"-"+m0+"px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])})}});$header_next.click(function(){if(inst.options.tabarrowmode=="switch")inst.switchNext();else if(inst.options.direction==
"horizontal"){var w0=inst.getTabElem(".wonderplugintabs-header-inner-wrap",inst.container).width();var w1=inst.calcHeaderUlWidth();var m0=Math.abs(parseFloat(inst.getTabElem(".wonderplugintabs-header-ul",inst.container).css("margin-left")))+w0;if(Math.ceil(m0)>=Math.floor(w1)&&inst.options.carouselloop)inst.getTabElem(".wonderplugintabs-header-ul",inst.container).animate({"margin-left":"0px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])});
else{if(m0>w1-w0){m0=w1-w0;if(!inst.options.carouselloop)$header_next.css({display:"none"})}inst.getTabElem(".wonderplugintabs-header-ul",inst.container).animate({"margin-left":"-"+m0+"px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])})}if(!inst.options.carouselloop)$header_prev.css({display:"block"})}else{var h0=inst.getTabElem(".wonderplugintabs-header-inner-wrap",inst.container).height()-Math.abs(parseFloat(inst.getTabElem(".wonderplugintabs-header-inner-wrap",
inst.container).css("padding-top")));var h1=inst.getTabElem(".wonderplugintabs-header-ul",inst.container).height();var m0=Math.abs(parseFloat(inst.getTabElem(".wonderplugintabs-header-ul",inst.container).css("margin-top")))+h0;if(m0>h1-h0)m0=h1-h0;inst.getTabElem(".wonderplugintabs-header-ul",inst.container).animate({"margin-top":"-"+m0+"px"},400,"easeOutCubic",function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])})}})}else if(this.options.responsivemode=="menu"){var $header_menu=
$('<div class="wonderplugintabs-header-menu"><div class="wonderplugintabs-header-menu-caption">'+(this.options.dropdownmenutext.length>0?'<span class="wonderplugintabs-header-menu-text">'+this.options.dropdownmenutext+"</span>":"")+'<span class="wonderplugintabs-header-menu-icon '+this.options.dropdownmenuicon+'"></span>'+"</div></div>");$header_wrap.append($header_menu);var $header_dropdown=$('<div class="wonderplugintabs-header-menu-dropdown"></div>');$header_wrap.append($header_dropdown);$header_menu.click(function(){if(inst.options.direction==
"horizontal")$header_dropdown.slideToggle();else $header_dropdown.fadeToggle()})}},updateHeaderNavs:function(){if(this.options.direction=="horizontal"&&this.options.responsivemode=="arrow"&&!this.options.carouselloop){var ml=Math.abs(parseFloat(this.getTabElem(".wonderplugintabs-header-ul",this.container).css("margin-left")));if(this.options.tabarrowmode=="slide"&&Math.floor(ml)<=0||this.options.tabarrowmode=="switch"&&this.getActiveId()==0)this.getTabElem(".wonderplugintabs-header-prev",this.container).css({display:"none"});
if(this.options.tabarrowmode=="switch"){var tabId=this.getActiveId();this.getTabElem(".wonderplugintabs-header-prev",this.container).css({display:tabId==0?"none":"block"});this.getTabElem(".wonderplugintabs-header-next",this.container).css({display:tabId==this.getTabElem(".wonderplugintabs-header-li",this.container).length-1?"none":"block"})}}},calcHeaderUlWidth:function(){var w=0;for(var i=0;i<this.getTabElem(".wonderplugintabs-header-li",this.container).length;i++){var item=this.getTabElem(".wonderplugintabs-header-li",
this.container).eq(i);w+=item.outerWidth()+parseFloat(item.css("margin-left"))+parseFloat(item.css("margin-right"))}return w},adjustHorArrowsTabPos:function(){var $header_wrap=this.getTabElem(".wonderplugintabs-header-wrap",this.container);var $header_ul=this.getTabElem(".wonderplugintabs-header-ul",this.container);var inst=this;if(this.options.responsivemode=="arrow"){var w0=$header_wrap.width();var w1=this.calcHeaderUlWidth();if(w1>w0){var tabid=$header_ul.data("activeid");if(tabid<0)tabid=0;var m0=
Math.abs(parseFloat(this.getTabElem(".wonderplugintabs-header-ul",this.container).css("margin-left")));var m1=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).position().left;var w2=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).outerWidth(true);var w3=this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).width();if(w1>w3&&m0>w1-w3)m0=w1-w3;var p=-m0;if(m0+w3<m1+w2)p=w3-m1-w2;else if(m0>m1)p=-m1;$header_ul.css({"float":"none"});$header_ul.stop().animate({"margin-left":p+
"px"},this.options.headeranimationduration,function(){$(window).trigger("carouselanimationfinished.wonderplugintabs",[inst.id])})}else{$header_ul.css({"margin-left":0});this.addHorFloat()}}else if(this.options.responsivemode=="menu"){var w0=$header_wrap.width();var w1=this.calcHeaderUlWidth();if(w1>w0)$header_ul.css({"float":"none"});else this.addHorFloat()}},adjustVertArrowsTabPos:function(){var $header_wrap=this.getTabElem(".wonderplugintabs-header-wrap",this.container);var $header_ul=this.getTabElem(".wonderplugintabs-header-ul",
this.container);if(this.options.responsivemode=="arrow"){var h0=$header_wrap.height();var h1=$header_ul.height();if(h1>h0){this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).addClass("wonderplugintabs-header-inner-wrap-arrows");var tabid=$header_ul.data("activeid");if(tabid<0)tabid=0;var m0=Math.abs(parseFloat(this.getTabElem(".wonderplugintabs-header-ul",this.container).css("margin-top")));var m1=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).position().top;
var h2=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).outerHeight()+parseFloat(this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).css("margin-top"))+parseFloat(this.getTabElem(".wonderplugintabs-header-li",this.container).eq(tabid).css("margin-bottom"));var h3=this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).height();var p=-m0;if(m0+h3<m1+h2)p=h3-m1-h2;else if(m0>m1)p=-m1;$header_ul.css({"margin-top":p+"px"})}else{this.getTabElem(".wonderplugintabs-header-inner-wrap",
this.container).removeClass("wonderplugintabs-header-inner-wrap-arrows");$header_ul.css({"margin-top":0})}}},checkMK:function(){if(this.options.stamp=="AM"+"FE"){var panel=this.getTabElem(".wonderplugintabs-panel",this.container);var mklink=$('a[href="'+this.options.marklink+'"]',panel);if(panel.text().indexOf(this.options.mark)<0||mklink.length<0)panel.append('<a href="'+this.options.marklink+'" target="_blank"><div style="display:block!important;visibility:visible!important;z-index:999;position:absolute;bottom:4px;right:4px;padding:3px;border-radius:3px;-moz-border-radius:3px;-webkit-border-radius:3px;background-color:#777;color:#fff;font:12px Arial,sans-serif;">'+
this.options.mark+"</div></a>");else if(mklink.css("display")=="none"||mklink.css("visibility")=="hidden"||parseInt(mklink.css("font-size"))<8||$("div",mklink).css("display")=="none"||$("div",mklink).css("visibility")=="hidden"||parseInt($("div",mklink).css("font-size"))<8){mklink.attr({style:mklink.attr("style")||""+"display:block!important;visibility:visible!important;font-size:12px!important;"});$("div",mklink).attr({style:$("div",mklink).attr("style")+"display:block!important;visibility:visible!important;font-size:12px!important;"})}}},
applyResponsive:function(){var inst=this;var screenWidth=$(window).width();if(!this.options.accordion&&this.options.accordiononsmallscreen)if(screenWidth<this.options.fullwidthtabsonsmallscreenwidth){this.accordionmode=true;this.applyAccordion()}else{this.accordionmode=false;this.reverseAccordion()}this.checkMK();this.updateNavsOnResponsive();this.adjustPanelHeight();if(this.options.fullwidthtabs||this.options.fullwidthtabsonsmallscreen&&screenWidth<this.options.fullwidthtabsonsmallscreenwidth){this.getTabElem(".wonderplugintabs-header-wrap",
this.container).addClass("wonderplugintabs-header-wrap-fullwidth");this.getTabElem(".wonderplugintabs-header-ul",this.container).addClass("wonderplugintabs-header-ul-fullwidth");this.getTabElem(".wonderplugintabs-header-li",this.container).addClass("wonderplugintabs-header-li-fullwidth");this.getTabElem(".wonderplugintabs-panel-wrap",this.container).addClass("wonderplugintabs-panel-wrap-fullwidth")}else{this.getTabElem(".wonderplugintabs-header-wrap",this.container).removeClass("wonderplugintabs-header-wrap-fullwidth");
this.getTabElem(".wonderplugintabs-header-ul",this.container).removeClass("wonderplugintabs-header-ul-fullwidth");this.getTabElem(".wonderplugintabs-header-li",this.container).removeClass("wonderplugintabs-header-li-fullwidth");this.getTabElem(".wonderplugintabs-panel-wrap",this.container).removeClass("wonderplugintabs-panel-wrap-fullwidth")}if(this.options.fullwidthtabs||this.options.fullwidthtabsonsmallscreen&&screenWidth<this.options.fullwidthtabsonsmallscreenwidth){this.getTabElem(".wonderplugintabs-header-ul",
this.container).css({"float":"none"});this.getTabElem(".wonderplugintabs-header-li",this.container).css({visibility:"visible"});this.getTabElem(".wonderplugintabs-header-title",this.container).css({display:this.options.usetablecellfortitle?"table-cell":"inline-block"});this.getTabElem(".wonderplugintabs-header-wrap",this.container).css({"padding-top":0,"padding-bottom":0,height:"auto"});this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).css({"margin-left":0,"margin-right":0});this.getTabElem(".wonderplugintabs-header-menu",
this.container).css({display:"none"});this.getTabElem(".wonderplugintabs-header-prev",this.container).css({display:"none"});this.getTabElem(".wonderplugintabs-header-next",this.container).css({display:"none"});return}if(this.options.hidetitleonsmallscreen)this.getTabElem(".wonderplugintabs-header-title",this.container).css({display:this.options.hidetitleonsmallscreenwidth>=screenWidth?"none":this.options.usetablecellfortitle?"table-cell":"inline-block"});if(this.options.direction=="horizontal"){var $header_wrap=
this.getTabElem(".wonderplugintabs-header-wrap",this.container);var $header_ul=this.getTabElem(".wonderplugintabs-header-ul",this.container);var w0=$header_wrap.width();var h0=$header_ul.height();var w1=0;for(var i=0;i<this.getTabElem(".wonderplugintabs-header-li",this.container).length;i++){var item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(i);w1+=item.outerWidth();if(this.options.responsivemode=="arrow"&&this.options.fixedheaderwidth&&this.options.fixedheaderinfull)w1+=2*
this.options.fixedheaderminimummargin;else w1+=parseFloat(item.css("margin-left"))+parseFloat(item.css("margin-right"))}if(this.options.responsivemode=="arrow"){var $header_prev=this.getTabElem(".wonderplugintabs-header-prev",this.container);var $header_next=this.getTabElem(".wonderplugintabs-header-next",this.container);var arrow_w=this.options.horizontalarrowwidthsameasheight=="sameheight"?h0:this.options.horizontalarrowwidth;if(w1>w0){this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).css({"margin-left":arrow_w+
"px","margin-right":arrow_w+"px"});$header_prev.css({display:"block",width:arrow_w+"px",height:h0+"px"});$header_next.css({display:"block",width:arrow_w+"px",height:h0+"px"});this.getTabElem(".wonderplugintabs-header-li-first",this.container).addClass("wonderplugintabs-header-li-first-side-arrows");this.getTabElem(".wonderplugintabs-header-li-last",this.container).addClass("wonderplugintabs-header-li-last-side-arrows")}else{this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).css({"margin-left":0,
"margin-right":0});$header_prev.css({display:"none"});$header_next.css({display:"none"});this.getTabElem(".wonderplugintabs-header-li-first",this.container).removeClass("wonderplugintabs-header-li-first-side-arrows");this.getTabElem(".wonderplugintabs-header-li-last",this.container).removeClass("wonderplugintabs-header-li-last-side-arrows")}if(this.options.fixedheaderwidth&&this.options.fixedheaderinfull){var $header_inner_wrap=this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container);
var innerWidth=$header_inner_wrap.width();var header_count=Math.floor(innerWidth/(this.options.headerwidth+2*this.options.minimumheadermargin));if(header_count<1)header_count=1;var header_margin=($header_inner_wrap.width()/header_count-this.options.headerwidth)/2;for(var i=0;i<this.getTabElem(".wonderplugintabs-header-li",this.container).length;i++){var item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(i);item.css({"margin-right":header_margin+"px","margin-left":header_margin+
"px"})}}this.updateHeaderNavs()}else if(this.options.responsivemode=="menu"){var $header_menu=this.getTabElem(".wonderplugintabs-header-menu",this.container);if(w1>w0){this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).css({"margin-right":h0+"px"});$header_menu.css({display:"table",height:h0+"px"});var w2=w0-h0;var w3=0;var i;for(i=0;i<this.getTabElem(".wonderplugintabs-header-li",this.container).length;i++){var item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(i);
w3+=item.outerWidth()+parseFloat(item.css("margin-left"))+parseFloat(item.css("margin-right"));if(w3>w2)break}this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).empty();for(var j=0;j<i;j++)this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).css({visibility:"visible"});for(var j=i;j<this.getTabElem(".wonderplugintabs-header-li",this.container).length;j++){this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).css({visibility:"hidden"});var code="";
var item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).find(".wonderplugintabs-header-icon-fontawesome");if(item.length>0)code+='<span class="'+item.attr("class")+'">'+item.html()+"</span>";item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).find(".wonderplugintabs-header-icon-image");if(item.length>0)code+='<img class="wonderplugintabs-header-icon-image" src="'+item.attr("src")+'" style="'+item.attr("style")+'" />';item=this.getTabElem(".wonderplugintabs-header-li",
this.container).eq(j).find(".wonderplugintabs-header-title");if(item.length>0)code+='<div class="wonderplugintabs-header-title">'+item.html()+"</div>";this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).append('<div class="wonderplugintabs-header-menu-dropdown-item" data-headerid="'+j+'">'+code+"</div>")}if(this.options.enabletabindex)$(".wonderplugintabs-header-menu-dropdown-item",this.container).attr("tabindex","0").keyup(function(e){if(e.keyCode==13)$(this).trigger("click")});
this.getTabElem(".wonderplugintabs-header-menu-dropdown-item",this.container).click(function(){var headerid=$(this).data("headerid");inst.switchToId(headerid)})}else{this.getTabElem(".wonderplugintabs-header-inner-wrap",this.container).css({"margin-right":0});this.getTabElem(".wonderplugintabs-header-li",this.container).css({visibility:"visible"});$header_menu.css({display:"none"});this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).css({display:"none"})}}this.adjustHorArrowsTabPos()}else{var $header_wrap=
this.getTabElem(".wonderplugintabs-header-wrap",this.container);var $header_ul=this.getTabElem(".wonderplugintabs-header-ul",this.container);var $panel_wrap=this.getTabElem(".wonderplugintabs-panel-wrap",this.container);var h0=$panel_wrap.outerHeight();var h1=$header_ul.height();if(this.options.autoexpandpanelheight&&h1>h0){$panel_wrap.css({"min-height":h1+"px"});this.adjustVertArrowsTabPos();return}if(this.options.responsivemode=="arrow"){var $header_prev=this.getTabElem(".wonderplugintabs-header-prev",
this.container);var $header_next=this.getTabElem(".wonderplugintabs-header-next",this.container);if(h1>h0){$header_prev.css({display:"block"});$header_next.css({display:"block"});$header_wrap.css({height:h0+"px","padding-top":$header_prev.height()+"px","padding-bottom":$header_next.height()+"px"});this.getTabElem(".wonderplugintabs-header-li-first",this.container).addClass("wonderplugintabs-header-li-first-side-arrows");this.getTabElem(".wonderplugintabs-header-li-last",this.container).addClass("wonderplugintabs-header-li-last-side-arrows")}else{$header_wrap.css({height:h0+
"px","padding-top":0,"padding-bottom":0});$header_prev.css({display:"none"});$header_next.css({display:"none"})}}else if(this.options.responsivemode=="menu"){var $header_menu=this.getTabElem(".wonderplugintabs-header-menu",this.container);if(h1>h0){$header_menu.css({display:"table"});$header_wrap.css({height:h0+"px","padding-bottom":$header_menu.outerHeight()+"px"});var h2=h0-$header_menu.outerHeight();var h3=0;var i;for(i=0;i<this.getTabElem(".wonderplugintabs-header-li",this.container).length;i++){var item=
this.getTabElem(".wonderplugintabs-header-li",this.container).eq(i);h3+=item.outerHeight()+parseFloat(item.css("margin-top"))+parseFloat(item.css("margin-bottom"));if(h3>h2)break}this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).empty();for(var j=0;j<i;j++)this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).css({visibility:"visible"});for(var j=i;j<this.getTabElem(".wonderplugintabs-header-li",this.container).length;j++){this.getTabElem(".wonderplugintabs-header-li",
this.container).eq(j).css({visibility:"hidden"});var code="";var item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).find(".wonderplugintabs-header-icon-fontawesome");if(item.length>0)code+='<span class="'+item.attr("class")+'">'+item.html()+"</span>";item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).find(".wonderplugintabs-header-icon-image");if(item.length>0)code+='<img class="wonderplugintabs-header-icon-image" src="'+item.attr("src")+'" style="'+item.attr("style")+
'" />';item=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(j).find(".wonderplugintabs-header-title");if(item.length>0)code+='<div class="wonderplugintabs-header-title">'+item.html()+"</div>";this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).append('<div class="wonderplugintabs-header-menu-dropdown-item" data-headerid="'+j+'">'+code+"</div>")}if(this.options.enabletabindex)$(".wonderplugintabs-header-menu-dropdown-item",this.container).attr("tabindex","0").keyup(function(e){if(e.keyCode==
13)$(this).trigger("click")});this.getTabElem(".wonderplugintabs-header-menu-dropdown-item",this.container).click(function(){var headerid=$(this).data("headerid");inst.switchToId(headerid)})}else;}this.adjustVertArrowsTabPos()}},adjustPanelHeight:function(){if(this.options.heightmode=="fixed"){this.getTabElem(".wonderplugintabs-panel-wrap",this.container).css({"overflow-y":this.options.paneloverflowvisible?"visible":"auto"});if(this.options.applydisplaynonetohiddenpanel)this.getTabElem(".wonderplugintabs-panel",
this.container).css({display:"none"});this.getTabElem(".wonderplugintabs-panel-active",this.container).css({display:"block"})}else{this.getTabElem(".wonderplugintabs-panel-wrap",this.container).css({"overflow-y":this.options.paneloverflowvisible?"visible":"hidden"});if(this.options.heightmode=="auto"&&!this.options.extendedheight){var tabid=this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid");var h=this.getTabElem(".wonderplugintabs-panel",this.container).eq(tabid).outerHeight();
if(h<this.options.minheight)h=this.options.minheight;this.getTabElem(".wonderplugintabs-panel-wrap",this.container).css({height:"auto","min-height":h+"px"})}else if(this.options.heightmode=="auto"&&this.options.extendedheight){var h=0;this.getTabElem(".wonderplugintabs-panel",this.container).each(function(){var h0=$(this).outerHeight();if(h0>h)h=h0});if(h<this.options.minheight)h=this.options.minheight;this.getTabElem(".wonderplugintabs-panel-wrap",this.container).css({height:"auto","min-height":h+
"px"})}}},getActiveHeaderWidth:function(){return this.getTabElem(".wonderplugintabs-header-li-active",this.container).width()},getActiveTabCenterPos:function(){var headerRect=this.getTabElem(".wonderplugintabs-header-wrap",this.container).get(0).getBoundingClientRect();var activeTabRect=this.getTabElem(".wonderplugintabs-header-li-active",this.container).get(0).getBoundingClientRect();return activeTabRect.x-headerRect.x+activeTabRect.width/2},getTotalHeaderWidth:function(){var headerRect=this.getTabElem(".wonderplugintabs-header-wrap",
this.container).get(0).getBoundingClientRect();return headerRect.width},getActiveId:function(){return this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid")},getTotalTabs:function(){return this.getTabElem(".wonderplugintabs-header-li",this.container).length},switchPrev:function(){var new_id=this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid")-1;if(new_id<0)if(this.options.carouselloop)new_id=this.getTabElem(".wonderplugintabs-header-li",this.container).length-
1;else new_id=0;this.switchToId(new_id)},switchNext:function(){var new_id=this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid")+1;if(new_id>=this.getTabElem(".wonderplugintabs-header-li",this.container).length)if(this.options.carouselloop)new_id=0;else new_id=this.getTabElem(".wonderplugintabs-header-li",this.container).length-1;this.switchToId(new_id)},switchToId:function(new_id,closetab){var $header_li=this.getTabElem(".wonderplugintabs-header-li",this.container);var old_id=
this.accordionmode&&this.options.accordionmultiple?-1:this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid");$(window).trigger("beforeswitch.wonderplugintabs",[this.id,old_id,new_id]);if(closetab){$header_li.eq(new_id).removeClass("wonderplugintabs-header-li-active").removeClass("wonderplugintabs-header-li-active-first").removeClass("wonderplugintabs-header-li-active-last");this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid",-1)}else{if(old_id>=0)$header_li.removeClass("wonderplugintabs-header-li-active").removeClass("wonderplugintabs-header-li-active-first").removeClass("wonderplugintabs-header-li-active-last");
$header_li.eq(new_id).addClass("wonderplugintabs-header-li-active");this.getTabElem(".wonderplugintabs-header-ul",this.container).data("activeid",new_id);if(new_id==0)$header_li.eq(new_id).addClass("wonderplugintabs-header-li-active-first");if(new_id==$header_li.length-1)$header_li.eq(new_id).addClass("wonderplugintabs-header-li-active-last");else if(this.options.responsivemode=="menu"&&new_id+1<=$header_li.length-1)if($header_li.eq(new_id+1).css("visibility")=="hidden")$header_li.eq(new_id).addClass("wonderplugintabs-header-li-active-last");
if(old_id>=0)$header_li.removeClass("wonderplugintabs-header-li-prev").removeClass("wonderplugintabs-header-li-next");var prev_tab=new_id-1;if(prev_tab>=0)$header_li.eq(prev_tab).addClass("wonderplugintabs-header-li-prev");var next_tab=new_id+1;if(next_tab<$header_li.length)$header_li.eq(next_tab).addClass("wonderplugintabs-header-li-next")}var effect=this.options.transition;if(effect){effect=effect.split(",");effect=effect[Math.floor(Math.random()*effect.length)];effect=$.trim(effect.toLowerCase())}if(this.accordionmode)effect=
"";if(this.options.onswitch&&window[this.options.onswitch]&&typeof window[this.options.onswitch]=="function")window[this.options.onswitch](old_id,new_id);if(closetab)this.switchEffect(new_id,-1,effect);else this.switchEffect(old_id,new_id,effect);if(this.options.direction=="horizontal")this.adjustHorArrowsTabPos();else this.adjustVertArrowsTabPos();this.updateArrows();this.updateNavs();this.updateHeaderNavs();this.getTabElem(".wonderplugintabs-header-menu-dropdown",this.container).hide();$(window).trigger("afterswitch.wonderplugintabs",
[this.id,old_id,new_id]);if(this.options.ajaxloading)this.ajaxLoadingTab(new_id);if(this.options.enablega&&this.options.gatrackingid&&window.ga){var page=document.location.pathname+document.location.search;if(page.indexOf("tabid=")>=0)page=page.replace(/tabid=\d+/g,"tabid="+new_id);else page+=(page.indexOf("?")<0?"?":"&")+"tabid="+new_id;ga("send","pageview",page)}if(!closetab&&this.options.savestatusincookie)$.wptCookie("wonderplugin_tabs_"+this.id+"_id",new_id);if(this.options.triggerresize)setTimeout(function(){$(window).trigger("resize")},
this.options.triggerresizetimeout)},ajaxLoadingTab:function(tabid){var currentPanel=this.getTabElem(".wonderplugintabs-panel",this.container).eq(tabid);var innerPanel=$(".wonderplugintabs-panel-inner",currentPanel);if(typeof wonderplugintabs_ajaxobject==="undefined"){innerPanel.html("AJAX content loading is disabled");return}if(!currentPanel.data("contentloaded")){currentPanel.css({"background-image":"url("+this.options.ajaxloadinggif+")","background-repeat":"no-repeat","background-position":"center center"});
this.ajaxLoadingTabContent(tabid)}},ajaxLoadingTabContent:function(tabid){var instance=this;var currentPanel=instance.getTabElem(".wonderplugintabs-panel",instance.container).eq(tabid);var innerPanel=$(".wonderplugintabs-panel-inner",currentPanel);jQuery.ajax({url:wonderplugintabs_ajaxobject.ajaxurl,type:"POST",data:{action:"wonderplugin_tabs_get_tab_content",nonce:wonderplugintabs_ajaxobject.nonce,id:instance.id,tabid:tabid},success:function(data){if(data)if(data.success&&data.content)innerPanel.html(data.content);
else if(data.message)innerPanel.html(data.message)},error:function(){innerPanel.html("Cannot AJAX load tab content")},complete:function(){currentPanel.data("contentloaded",1).css({"background-image":"none"});$(window).trigger("ajaxloaded.wonderplugintabs",[instance.id,tabid])}})},switchTabs:function(){var inst=this;this.getTabElem(".wonderplugintabs-header-caption",this.container).click(function(){var $header=$(this).closest(".wonderplugintabs-header-li");if(inst.accordionmode&&$header.hasClass("wonderplugintabs-header-li-active")){inst.switchToId($header.index(),
true);return}if($header.hasClass("wonderplugintabs-header-li-active"))return;inst.switchToId($header.index())});if(this.options.switchonmouseover)this.getTabElem(".wonderplugintabs-header-caption",this.container).on("mouseover",function(){var $header=$(this).closest(".wonderplugintabs-header-li");if($header.hasClass("wonderplugintabs-header-li-active"))return;inst.switchToId($header.index())})},switchEffect:function(old_id,new_id,effect){var inst=this;if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",
this.container).eq(old_id).removeClass("wonderplugintabs-panel-active");if(new_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(new_id).addClass("wonderplugintabs-panel-active");this.applyResponsive();if(old_id==new_id)return;if(this.accordionmode&&this.options.accordionadjustposition&&!this.options.accordionmultiple&&new_id>0&&old_id>=0&&new_id>old_id){var pos=this.getTabElem(".wonderplugintabs-header-li",this.container).eq(new_id).offset().top-this.getTabElem(".wonderplugintabs-panel",
this.container).eq(old_id).outerHeight();var scroll_top=$(window).scrollTop();if(scroll_top>pos)$(window).scrollTop(pos)}if(effect=="fade"){if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(old_id).fadeTo(400,0,function(){if(inst.options.applydisplaynonetohiddenpanel)$(this).css({display:"none"});$(this).css({opacity:0,visibility:"hidden"})});if(new_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(new_id).css({display:"block",opacity:0,visibility:"visible"}).fadeTo(400,
1)}else if(effect=="fadeout")if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(old_id).fadeTo(400,0,function(){if(inst.options.applydisplaynonetohiddenpanel)$(this).css({display:"none"});$(this).css({opacity:0,visibility:"hidden"});if(new_id>=0)inst.getTabElem(".wonderplugintabs-panel",inst.container).eq(new_id).css({display:"block",opacity:0,visibility:"visible"}).fadeTo(400,1)});else{if(new_id>=0)inst.getTabElem(".wonderplugintabs-panel",inst.container).eq(new_id).css({display:"block",
opacity:0,visibility:"visible"}).fadeTo(400,1)}else if(effect=="slide")if(new_id>old_id){if(new_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(new_id).css({left:"100%",display:"block",visibility:"visible",opacity:1}).animate({left:0},400);if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(old_id).animate({left:"-100%"},400,function(){if(inst.options.applydisplaynonetohiddenpanel)$(this).css({display:"none"});$(this).css({visibility:"hidden",opacity:0,left:0})})}else{if(new_id>=
0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(new_id).css({left:"-100%",display:"block",visibility:"visible",opacity:1}).animate({left:0},400);if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(old_id).animate({left:"100%"},400,function(){if(inst.options.applydisplaynonetohiddenpanel)$(this).css({display:"none"});$(this).css({visibility:"hidden",opacity:0,left:0})})}else{if(inst.options.applydisplaynonetohiddenpanel&&old_id>=0)this.getTabElem(".wonderplugintabs-panel",
this.container).eq(old_id).css({display:"none"});if(old_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(old_id).css({visibility:"hidden",opacity:0});if(new_id>=0)this.getTabElem(".wonderplugintabs-panel",this.container).eq(new_id).css({display:"block",visibility:"visible",opacity:1})}}};options=options||{};for(var key in options)if(key.toLowerCase()!==key){options[key.toLowerCase()]=options[key];delete options[key]}this.each(function(){if($(this).data("donotinit")&&(!options||!options["forceinit"]))return;
if($(this).data("inited"))return;$(this).data("inited",1);var defaultOptions={minheight:300,triggerresizeonload:true,triggerresizeonloadtimeout:100,triggerresize:true,triggerresizetimeout:10,horizontalarrowwidthsameasheight:"pixels",horizontalarrowwidth:32,fullwidthtabs:false,accordion:false,accordionmultiple:false,accordioncloseall:false,accordionadjustposition:true,closeall:false,fullwidthtabsonsmallscreen:false,fullwidthtabsonsmallscreenwidth:480,applydisplaynonetohiddenpanel:true,savestatusincookie:false,
keyaccess:false,enabletabindex:false,accordiononsmallscreen:false,switchonmouseover:false,fixedheaderwidth:false,fixedheaderheight:false,fixedheaderinfull:true,headerwidth:180,headerheight:80,fixedheaderminimummargin:4,headeranimationduration:200,resizedelay:10,arrowfontsize:20,arrowfontcolor:"#666",usetablecellfortitle:false,ajaxloading:false,ajaxloadingfirst:false,ajaxloadinggif:"loading.gif",arrowstyle:"none",arrowimage:"arrows-32-32-2.png",arrowwidth:32,arrowheight:32,arrowloop:true,prevarrowcss:"position:absolute;top:50%;left:0;margin-top:-16px;",
nextarrowcss:"position:absolute;top:50%;right:0;margin-top:-16px;",arrowinsidepanel:true,navstyle:"none",navwidth:16,navheight:16,navspacing:8,navimage:"bullet-16-16-0.png",navcss:"display:block;position:relative;text-align:center;width:100%;top:100%;margin-top:16px;",navinsidepanels:false,navinpanelscenter:true,hidenavinaccordionmode:true,autoexpandpanelheight:false,paneloverflowvisible:false,addpanelarrow:false,minimumheadermargin:0,carouselloop:false,enablega:false,gatrackingid:""};this.options=
$.extend({},defaultOptions,options);var bts=function(string){var ret="";var bytes=string.split(",");for(var i=0;i<bytes.length;i++)ret+=String.fromCharCode(bytes[i]);return ret};this.options.mark=bts("87,111,114,100,80,114,101,115,115,32,84,97,98,115,32,84,114,105,97,108,32,86,101,114,115,105,111,110");this.options.marklink=bts("104,116,116,112,115,58,47,47,119,119,119,46,119,111,110,100,101,114,112,108,117,103,105,110,46,99,111,109,47,119,111,114,100,112,114,101,115,115,45,116,97,98,115,47");var instance=
this;$.each($(this).data(),function(key,value){instance.options[key.toLowerCase()]=value});if(this.options.fixedheadersize){this.options.fixedheaderwidth=true;this.options.fixedheaderheight=true}var image_list=["ajaxloadinggif","arrowimage","navimage"];for(var i=0;i<image_list.length;i++)if(this.options[image_list[i]]&&this.options[image_list[i]].length>0&&this.options[image_list[i]].substring(0,7).toLowerCase()!="http://"&&this.options[image_list[i]].substring(0,8).toLowerCase()!="https://")this.options[image_list[i]]=
this.options.jsfolder+this.options[image_list[i]];this.options.stamp="AMCom";var object=new WonderPluginTabs($(this),this.options,this.options.tabsid);$(this).data("object",object);$(this).data("id",this.options.tabsid);wonderpluginTabsObjects.addObject(object)})};$.wptCookie=function(key,value,options){if(typeof value!=="undefined"){options=$.extend({},{path:"/"},options);if(options.expires){var seconds=options.expires;options.expires=new Date;options.expires.setTime(options.expires.getTime()+seconds*
1E3)}return document.cookie=key+"="+encodeURIComponent(value)+(options.expires?";expires="+options.expires.toUTCString():"")+(options.path?";path="+options.path:"")}var result=null;var cookies=document.cookie?document.cookie.split(";"):[];for(var i in cookies){var parts=$.trim(cookies[i]).split("=");if(parts.length&&parts[0]==key){result=decodeURIComponent(parts[1]);break}}return result};$.wptRemoveCookie=function(key){return $.wptCookie(key,"",$.extend({},{expires:-1}))}})(jQuery);
(function($){var pow=Math.pow,sqrt=Math.sqrt,sin=Math.sin,cos=Math.cos,PI=Math.PI,c1=1.70158,c2=c1*1.525,c3=c1+1,c4=2*PI/3,c5=2*PI/4.5;function bounceOut(x){var n1=7.5625,d1=2.75;if(x<1/d1)return n1*x*x;else if(x<2/d1)return n1*(x-=1.5/d1)*x+0.75;else if(x<2.5/d1)return n1*(x-=2.25/d1)*x+0.9375;else return n1*(x-=2.625/d1)*x+0.984375}$.extend($.easing,{def:"easeOutQuad",easeInQuad:function(x){return x*x},easeOutQuad:function(x){return 1-(1-x)*(1-x)},easeInOutQuad:function(x){return x<0.5?2*x*x:1-
pow(-2*x+2,2)/2},easeInCubic:function(x){return x*x*x},easeOutCubic:function(x){return 1-pow(1-x,3)},easeInOutCubic:function(x){return x<0.5?4*x*x*x:1-pow(-2*x+2,3)/2},easeInQuart:function(x){return x*x*x*x},easeOutQuart:function(x){return 1-pow(1-x,4)},easeInOutQuart:function(x){return x<0.5?8*x*x*x*x:1-pow(-2*x+2,4)/2},easeInQuint:function(x){return x*x*x*x*x},easeOutQuint:function(x){return 1-pow(1-x,5)},easeInOutQuint:function(x){return x<0.5?16*x*x*x*x*x:1-pow(-2*x+2,5)/2},easeInSine:function(x){return 1-
cos(x*PI/2)},easeOutSine:function(x){return sin(x*PI/2)},easeInOutSine:function(x){return-(cos(PI*x)-1)/2},easeInExpo:function(x){return x===0?0:pow(2,10*x-10)},easeOutExpo:function(x){return x===1?1:1-pow(2,-10*x)},easeInOutExpo:function(x){return x===0?0:x===1?1:x<0.5?pow(2,20*x-10)/2:(2-pow(2,-20*x+10))/2},easeInCirc:function(x){return 1-sqrt(1-pow(x,2))},easeOutCirc:function(x){return sqrt(1-pow(x-1,2))},easeInOutCirc:function(x){return x<0.5?(1-sqrt(1-pow(2*x,2)))/2:(sqrt(1-pow(-2*x+2,2))+1)/
2},easeInElastic:function(x){return x===0?0:x===1?1:-pow(2,10*x-10)*sin((x*10-10.75)*c4)},easeOutElastic:function(x){return x===0?0:x===1?1:pow(2,-10*x)*sin((x*10-0.75)*c4)+1},easeInOutElastic:function(x){return x===0?0:x===1?1:x<0.5?-(pow(2,20*x-10)*sin((20*x-11.125)*c5))/2:pow(2,-20*x+10)*sin((20*x-11.125)*c5)/2+1},easeInBack:function(x){return c3*x*x*x-c1*x*x},easeOutBack:function(x){return 1+c3*pow(x-1,3)+c1*pow(x-1,2)},easeInOutBack:function(x){return x<0.5?pow(2*x,2)*((c2+1)*2*x-c2)/2:(pow(2*
x-2,2)*((c2+1)*(x*2-2)+c2)+2)/2},easeInBounce:function(x){return 1-bounceOut(1-x)},easeOutBounce:bounceOut,easeInOutBounce:function(x){return x<0.5?(1-bounceOut(1-2*x))/2:(1+bounceOut(2*x-1))/2}})})(jQuery);jQuery(document).ready(function(){jQuery(".wonderplugin-tabs-engine").css({display:"none"});if(jQuery.fn.wonderplugintabs)jQuery(".wonderplugintabs").wonderplugintabs()});
